greenbone/vt-test-environments

.github/workflows/build.yml, README.md
**What**:
This PR adds AlmaLinux 8.4.
**Why**:
To have it available for testing.
Note that the AlmaLinux 8.3 repo is still working too, but there's no base image on Docker Hub, so some additional work would be required to get it working as well.
**How**:
Spun up a container using this image, ran `dnf update` to check for any updates, checked `/etc/os-release` for the correct content, SSH'ed into the container using the demo account
=> Add AlmaLinux 8.4

.github/workflows/build.yml, README.md
**What**:
This PR adds AlmaLinux 8.7 and 9.1.
**Why**:
To have them available for testing.
**How**:
Built both images, confirmed that the dnf update / install is working, ssh'ed into them and checked `/etc/os-release` for correct release.
**Checklist**:
=> Add AlmaLinux 8.7 and 9.1

tools/run_all.sh
**What**:
This PR adds a script to run all images of an OS easily.
**Why**:
Instead of looking up the tags of available images, manually starting and stopping then, this script will take care of it. This eases testing a change in multiple environments (e.g. all Ubuntu images).
The script provides to modes: One for executing a specific command in all environments and another for only starting the container to have it available for SSH-based scanning.
**How**:
**Checklist**:
=> Add script for running all test environments

.github/workflows/build.yml
This PR adds checks for new PRs, but running the workflow for building and testing while skipping the push to ghcr.
To build and test the container images before merging them to main.
Jira: https://jira.greenbone.net/browse/VTA-400
=> Add PR checks

.github/workflows/build.yml
This PR fixes the output of the container test for e.g. https://github.com/greenbone/vt-test-environments/actions/runs/4185410682/jobs/7252429292#step:6:20.
No all distributions come with `hostname`, so the hostname will be blank then:
```
[...]
Warning: Permanently added '[localhost]:2222' (ED25519) to the list of known hosts.
bash: line 1: hostname: command not found
Hello from demo@
[...]
```
We can easily work around this by `cat`ing the file directly.
=> Fix output in container test

.github/workflows/build.yml, README.md, operating_systems/rhel/Dockerfile
This PR adds Red Hat Enterprise Linux 7.6 through 7.9, 8.0 through 8.7 as well as 9.0.0 and 9.1.0.
To have them available for testing.
=> Add Red Hat Enterprise Linux

.github/workflows/build.yml, README.md
Adding ubuntu 23.04 (Lunar Lobster) to the repo.
- OS detection works
- Package detection works
See test output below.
Closes: VTA-428
=> Add build and readme for Ubuntu 23.04 Lunar Lobster

.github/workflows/build.yml
This PR disables the build of images for Debian Jessie and Stretch, until the underlying issue is fixed.
The build is [failing](https://github.com/greenbone/vt-test-environments/actions/runs/4959464632) because of https://github.com/debuerreotype/docker-debian-eol-artifacts/issues/8.
We could also fix this on our side, but that's probably not worth it.
=> Temporarily disable Debian Jessie and Stretch

.github/workflows/build.yml
This PR fixes the insufficient package write permissions in the build workflow, see https://github.com/greenbone/vt-test-environments/actions/runs/4979904780.
To be able to push images again.
=> Fix package write permissions in build workflow

applications/home-assistant/Dockerfile
This PR fixes the build of the Home Assistant image.
It's cause by `openssh-client` being already installed and `openssh` (that's client + server) conflicting with it. After removing the former, the latter can be installed without issues.
To have it building again and get rid off the red X on the build workflow.
=> Fix Home Assistant build

.github/workflows/build.yml, README.md, operating_systems/openeuler/Dockerfile
This PR adds container images for openEuler.
I chose the latest ones from https://hub.docker.com/r/openeuler/openeuler, until the previous LTS release except for 22.09 (that one would need additional adjustments).
To have them available for testing.
=> Add openEuler

operating_systems/oraclelinux/Dockerfile, operating_systems/rhel/Dockerfile
@cfi-gb noticed that two Dockerfiles were missing the `EXPOSE` statement. I can confirm his findings:
```
➜  vt-test-environments git:(main) rg -g Dockerfile --files-without-match EXPOSE
operating_systems/rhel/Dockerfile
operating_systems/oraclelinux/Dockerfile
```
Because it should be in there, but looks like we missed it.
=> Add: Missing EXPOSE to Oracle and RHEL Dockerfiles

.github/CODEOWNERS
See title
While the automation team members are also in the vt team group this repo is mainly managed by the first team and this change makes this a little bit more clear / visible
N/A
=> Change: Extend CODEOWNERS file with automation team specific group.

operating_systems/slackware/Dockerfile
This PR fixes the build of Slackware current.
Because it's failing due to an outdated libc. Updating is was a little tricky, because at some point in the installation of packages failed due to some GPG issues (gnupg has been updated right before).
I tried several approaches, but only running `upgrade-all` twice (allowing failure only in the first run, then fixing those in the second) was reliable.
This makes https://github.com/greenbone/vt-test-environments/pull/62 obsolete.
=> Change: Fix Slackware current

.github/workflows/build.yml
See title
24.10 has been already released on October 10, 2024 but not build yet, this should change.
None
=> Change: Build Ubuntu 24.10 image.

applications/oracle-weblogic/10.3.6.0-2017/Dockerfile, operating_systems/debian/Dockerfile, operating_systems/ubuntu/Dockerfile
https://packages.debian.org/bookworm/openssh-server has various `rec` dependencies to e.g. `xauth` which pulls in various (for us / our purposes) unnecessary X11 dependencies. After this change the image size got reduced from:
```
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
debian       12        bbd0a7b950d6   39 seconds ago   190MB
```
to:
```
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
debian       12        cc5a6cc10e13   27 seconds ago   162MB
```
without any functional limitations.
Note: Ubuntu failures seems to be unrelated to this PR and might be related to VTA-589
Reduce size of our images a little.
None
=> Change: Use --no-install-recommends for Debian/Ubuntu to reduce image size.

.github/workflows/build.yml, .github/workflows/dependency-review.yml, .github/workflows/sbom-upload.yml, README.md, applications/generic/Dockerfile, applications/home-assistant/Dockerfile, applications/oracle-weblogic/10.3.6.0-2017/Dockerfile, applications/oracle-weblogic/12.2.1.3-2018/Dockerfile, operating_systems/almalinux/Dockerfile, operating_systems/amazonlinux/Dockerfile, operating_systems/debian/Dockerfile, operating_systems/euleros/Dockerfile, operating_systems/fedora/Dockerfile, operating_systems/mageia/Dockerfile, operating_systems/openeuler/Dockerfile, operating_systems/oraclelinux/Dockerfile, operating_systems/rockylinux/Dockerfile, operating_systems/slackware/Dockerfile, operating_systems/ubuntu/Dockerfile
This PR
- changes Docker with Podman / Buildah to build, test and push our images (fixes currently broken workflow)
- disables updating of images by default
- includes the registry in the baseimage name
- pins our workflow dependencies.
Docker dropped support for Docker Image Format v1 and Docker Image manifest version 2, schema 1. Old images, like we are depending on in this repo, are still using those deprecated versions though. Buildah / Podman still have support for those.
If those older images are converted to version 2, schema 2 at some point, we could go back to Docker.
I also disabled the updating of images by default. My intention back then was to provide mostly up-to-date images, but we actually want rather non-update / vulnerable images in this repo. Besides that, updating the …
=> Refactor image building (e.g. using Buildah instead of Docker)

operating_systems/rhel/Dockerfile
`yum clean all` was only called before the installation of additional packages and only in the case if `UPDATED=true` was used.
Before this change:
```
$ docker image ls rhel:8.7
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
rhel         8.7       4cc316416a53   11 seconds ago   234MB
```
after this change:
```
$ docker image ls rhel:8.7
REPOSITORY   TAG       IMAGE ID       CREATED         SIZE
rhel         8.7       ade26e58d71d   7 seconds ago   225MB
```
Reduce image size (not much but still worth a minor change like this)
None
=> Change: Reduce RHEL image size by calling "yum clean all" after installing packages.

.github/workflows/build.yml
This PR fixes the Oracle Weblogic image tag.
Because it currently gets published as e.g. `ghcr.io/greenbone/vt-test-environments/10.3.6.0-2017:10.3.6.0-2017` instead of `ghcr.io/greenbone/vt-test-environments/oracle-weblogic:10.3.6.0-2017`.
This issue was introduced in https://github.com/greenbone/vt-test-environments/pull/60.
I checked that the Oracle images are now built with `tags: ghcr.io/greenbone/vt-test-environments/oracle-weblogic:12.2.1.3-2018` instead of `tags: ghcr.io/greenbone/vt-test-environments/12.2.1.3-2018:12.2.1.3-2018`.
I also checked a few other images to confirm that they're still built with the same tag.
=> Change: Fix Oracle Weblogic image tag

.github/workflows/build.yml
This PR adds the possibility to explicitly specify a tag for the exported image. If not specified, it'll keep using the tag of the source image.
For https://github.com/greenbone/vt-test-environments/pull/77 we need to use the image `tumbleweed:latest`, but want to export is as `opensuse:tumbleweed` instead. This is not possible with the current behavior.
I tested this using two Ubuntu images in https://github.com/greenbone/vt-test-environments/actions/runs/12647975873?pr=79. 
Without any `EXPORT_TAG` the image us built using
```
Run redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056
with:
context: operating_systems/ubuntu
containerfiles: operating_systems/ubuntu/Dockerfile
tags: ghcr.io/greenbone/vt-test-environments/ubuntu:24.04
build-args: TAG=24.04
[...]
✅ …
```
=> Export images with different tags than their source

operating_systems/fedora/Dockerfile, operating_systems/oraclelinux/Dockerfile
This PR disables PAM for Fedora and Oracle.
Because the build for Fedora 40 and Oracle 8 & 9 are currently broken, because PAM during SSH authentication is not working correctly in Podman. See the Jira ticket for more information.
Disabling PAM is officially not supported in Fedora & Oracle, but I couldn't find anything broken for our use-case.
For Fedora and Oracle 9 I simply created an additional config file to disable PAM, for Oracle 8 (which doesn't use `.d`-config files by default) I edited the main config.
Jira: https://jira.greenbone.net/browse/VTA-641
I've built the containers for Fedora 39 and 40 as well as Oracle 7, 8 and 9. They are working again / working as expected.
=> Work around broken SSH login by disabling PAM for Fedora and Oracle

operating_systems/openeuler/Dockerfile
This PR fixes the build of the openEuler 20.03-lts image.
Do make it working again.
For whatever reason, installing `openssh-server` tries to downgrade `openssh` (a dependencies of `openssh-server`) to a version that isn't signed. This is why the build is failing.
Luckily, openEuler 20.03-lts already comes with a `openssh-server` preinstalled, so we can just skip the installation.
Installing only `openssh`, which for whatever reason depends in `openssh-server` would also solve the issue, but that'd be a little weird.
=> Fix openEuler 20.04-lts

.github/workflows/build.yml, README.md
This PR fixes the ordering of builds & tags.
Because I incorrectly changed the ordering in https://github.com/greenbone/vt-test-environments/pull/89 + noticed that Oracle WebLogic Server wasn't in order.
=> Fix ordering

operating_systems/euleros/Dockerfile
This PR disables PAM for EulerOS, similar to https://github.com/greenbone/vt-test-environments/pull/82.
Because it's apparently also affected by https://jira.greenbone.net/browse/VTA-641, see https://github.com/greenbone/vt-test-environments/actions/runs/14055302493/job/39353400680#step:6:19.
Relates to https://github.com/greenbone/vt-test-environments/pull/82 / https://jira.greenbone.net/browse/VTA-641.
Checked that EulerOS 2.9 is now working again.
=> Change: Disable PAM for EulerOS to work around broken SSH login
